STARTING AT Wed Aug 17 15:15:31 CEST 2022
06serialCorrelation.py
Traceback (most recent call last):
  File "/home/bierlair/biogeme-3.2.9/biogeme/results.py", line 336, in __init__
    with open(pickleFile, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '05latentChoiceFull.pickle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "06serialCorrelation.py", line 46, in <module>
    results = res.bioResults(pickleFile='05latentChoiceFull.pickle')
  File "/home/bierlair/biogeme-3.2.9/biogeme/results.py", line 340, in __init__
    raise excep.biogemeError(error_msg) from e
biogeme.exceptions.biogemeError: File 05latentChoiceFull.pickle not found
srun: error: h151: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2169803.0
FINISHED AT Wed Aug 17 15:15:32 CEST 2022
